service: online-feed-backend-for-frontend
provider:
  name: aws
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  logs:
    restApi: true

  environment:
    SQS_QUEUE_URL:
      Ref: FeedQueue

  iamRoleStatements:
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: "arn:aws:execute-api:*:*:*/development/POST/@connections/*"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - { Fn::GetAtt: ["FeedPostsTable", "Arn"] }
        - { Fn::GetAtt: ["UsersTable", "Arn"] }
        - { Fn::GetAtt: ["ConnectionsDynamoDBTable", "Arn"] }
        - { Fn::GetAtt: ["SubscriptionsDynamoDBTable", "Arn"] }
        - { Fn::GetAtt: ["SubscriptionOperationsDynamoDBTable", "Arn"] }
        - { Fn::GetAtt: ["EventsDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - { Fn::GetAtt: ["FeedQueue", "Arn"] }

functions:
  graphql:
    handler: src/server.graphqlHttpHandler
    events:
      - http:
          path: /
          method: any
          cors: true
  subscriptions-handler:
    handler: src/server.graphqlWebSocketHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  feed-stream-handler:
    handler: src/server.graphqlDynamoStreamHandler
    events:
      - http:
          path: /
          method: any
          cors: true
      - stream:
          type: dynamodb
          enabled: true
          arn: { Fn::GetAtt: ["EventsDynamoDBTable", "StreamArn"] }

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: online-feed-users

    FeedPostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: online-feed-posts

    FeedQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: online-feed-queue

    ConnectionsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # see DynamoDBConnectionManager
        TableName: Connections
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          # connection id
          - AttributeName: id
            KeyType: HASH

    SubscriptionsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # see DynamoDBSubscriptionManager
        TableName: Subscriptions
        AttributeDefinitions:
          - AttributeName: event
            AttributeType: S
          - AttributeName: subscriptionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: event
            KeyType: HASH
          - AttributeName: subscriptionId
            KeyType: RANGE

    SubscriptionOperationsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # see DynamoDBSubscriptionManager
        TableName: SubscriptionOperations
        AttributeDefinitions:
          - AttributeName: subscriptionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: subscriptionId
            KeyType: HASH

    EventsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # see DynamoDBEventStore
        TableName: Events
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        # see ISubscriptionEvent
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        StreamSpecification:
          StreamViewType: NEW_IMAGE
